CarDealership/Controllers/CustomerController.cs
using CarDealership.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Controllers
{
    public class CustomerController : Controller
    {

        // Define CarFunctions object
        private readonly CarFunctions _carFunctions;

        // Constructor for Controller
        // Initializes CarFunctions object to allow use of CarFunctions functions
        public CustomerController(CarFunctions carFunctions)
        { 
            _carFunctions = carFunctions;
        }

        // Returns Index view for the customer
        public ActionResult Index()
        {
            return View();
        }

        // Gets cars from database using getCars() function,
        // then returns Inventory view with cars' data
        public ActionResult Inventory()
        {
            var cars = _carFunctions.getCars();

            return View(cars);
        }

        // Gets car from database by Make and Model using getCarByMakeModel() function,
        // then returns car detail view with car's data
        [HttpGet]
        public ActionResult Car(string make, string model) 
        {
            var car = _carFunctions.getCarByMakeModel(make, model);

            return View(car);
        }

        // Returns Buy view
        public ActionResult Buy()
        {
            return View();
        }

        // Returns Search view
        public ActionResult Search() 
        {
            return View();
        }
    }
}

CarDealership/Controllers/IndexController.cs
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Controllers
{
    public class IndexController : Controller
    {

        // Returns default Index page for the web api
        public IActionResult Index()
        {
            return View();
        }
    }
}

CarDealership/Controllers/StaffController.cs
using CarDealership.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Controllers
{
    public class StaffController : Controller
    {
        
        // Defining CarFunctions and StaffFunctions objects
        private readonly CarFunctions _carFunctions;
        private readonly StaffFunctions _staffFunctions;

        // Constructor for Controller
        // Initializes CarFunctions and StaffFunctions objects,
        // to allow use of their functions
        public StaffController(CarFunctions carFunctions, StaffFunctions staffFunctions)
        {
            _carFunctions = carFunctions;
            _staffFunctions = staffFunctions;
        }

        // Returns Index view for the staff
        public ActionResult Index()
        {
            return View();
        }
        
        // Gets all cars from database table using getCars() function,
        // then returns the Inventory view with all cars' data
        public ActionResult Inventory()
        {
            var cars = _carFunctions.getCars();

            return View(cars);
        }

        // Gets car from database by plate number using getCarByPlate() function,
        // then returns the Car detail view
        [HttpGet]
        public ActionResult Car(int plateNum)
        {
            var car = _carFunctions.getCarByPlate(plateNum);

            return View(car);
        }

        // Returns Search view
        public ActionResult Search()
        {
            return View();
        }

        // Returns Sell view
        public ActionResult Sell()
        {
            return View();
        }

        // Gets car from database by plate number using getCarByPlate() function,
        // passes car into sellCar() function,
        // then returns Sold view with car's data
        [HttpGet]
        public ActionResult Sold(int plateNum)
        {
            var car = _carFunctions.getCarByPlate(plateNum);

            _carFunctions.sellCar(plateNum);

            return View(car);
        }

        // Returns CarForm view
        public ActionResult CarForm() 
        {
            return View();
        }

        // Adds car to database using addCar() function,
        // then returns Add view
        public ActionResult Add(int plateNum, int lotID, string make, string model,
            int modelYear, int price, string color, string carStatus, int salesmanID)
        {
            _carFunctions.addCar(plateNum, lotID, make, model, modelYear, price, color, carStatus, salesmanID);

            return View();
        }

        // Returns UpdateSearch view
        public ActionResult UpdateSearch()
        {
            return View();
        }

        // Finds car in database by plate number using getCarByPlate() function,
        // then returns UpdateForm view with car's data
        public ActionResult UpdateForm(int plateNum)
        {
            var car = _carFunctions.getCarByPlate(plateNum);

            return View(car);
        }

        // Updates car using updateCar() function,
        // then returns Update view
        public ActionResult Update(int plateNum, int lotID, string make, string model,
            int modelYear, int price, string color, string carStatus, int salesmanID) 
        {

            _carFunctions.updateCar(plateNum, lotID, make, model, modelYear, price, color, carStatus, salesmanID);

            return View();
        }

        // Returns MoveCarSearch view
        public ActionResult MoveCarSearch()
        {
            return View();
        }

        // Finds car in database by plate number using getCarByPlate() function
        // then returns MoveCarForm view with car's data
        public ActionResult MoveCarForm(int plateNum)
        {
            var car = _carFunctions.getCarByPlate(plateNum);

            return View(car);
        }

        // Updates car's LotID and CarStatus fields using updateCar() function,
        // then returns MoveCar view
        public ActionResult MoveCar(int plateNum, int lotID, string make, string model,
            int modelYear, int price, string color, string carStatus, int salesmanID)
        {

            // Updates car's LotID field to new LotID and sets car's CarStatus field to "InTransit",
            // using updateCar() function
            _carFunctions.updateCar(plateNum, lotID, make, model, modelYear, price, color, "InTransit", salesmanID);

            // (Lot transfer is now complete) Updates car's CarStatus field to "Available" using updateCar() function
            _carFunctions.updateCar(plateNum, lotID, make, model, modelYear, price, color, "Available", salesmanID);

            return View();
        }

        // Returns MaintenanceForm view
        public ActionResult MaintenanceForm() 
        { 
            return View();
        }

        // Updates car's CarStatus field using the updateCar() function,
        // then returns Maintenance view
        public ActionResult Maintenance(int plateNum, int lotID, string make, string model,
            int modelYear, int price, string color, string carStatus, int salesmanID)
        {
            _carFunctions.updateCar(plateNum, lotID, make, model, modelYear, price, color, carStatus, salesmanID);

            return View();
        }

        // Returns AssignSalesmanSearch view
        public ActionResult AssignSalesmanSearch() 
        {
            return View();
        }

        // Gets car from database by plate number using getCarByPlate() function
        // then returns AssignSalesmanForm view with car's data
        public ActionResult AssignSalesmanForm(int plateNum) 
        {
            var car = _carFunctions.getCarByPlate(plateNum);

            return View(car);
        }

        // Updates car's SalesmanID field using updateCar() function,
        // then returns AssignSalesman view
        public ActionResult AssignSalesman(int plateNum, int lotID, string make, string model,
            int modelYear, int price, string color, string carStatus, int salesmanID)
        {
            _carFunctions.updateCar(plateNum, lotID, make, model, modelYear, price, color, carStatus, salesmanID);

            return View();
        }

        // Returns SalesReportSearch view
        public ActionResult SalesReportSearch()
        {
            return View();
        }

        // Gets staff from database by StaffID field using getStaff() function,
        // then returns SalesReport view with staff's data
        public ActionResult SalesReport(int staffID)
        {
            var staff = _staffFunctions.getStaff(staffID);

            return View(staff);
        }
    }
}

CarDealership/Views/Customer/Car.cshtml
@{
    ViewData["Title"] = "View Car Details";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using CarDealership.Models
@model IEnumerable<Car>

<h2>Selected Car</h2>

<table>
    <tr>
        <th>Plate Number</th>
        <th>Lot Number</th>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>Price</th>
        <th>Color</th>
        <th>Condition</th>
        <th>Salesman ID Number</th>
    </tr>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>@car.PlateNumber</td>
                <td>@car.LotID</td>
                <td>@car.Make</td>
                <td>@car.Model</td>
                <td>@car.ModelYear</td>
                <td>@car.Price</td>
                <td>@car.Color</td>
                <td>@car.CarStatus</td>
                <td>@car.SalesmanID</td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Customer" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Customer/Inventory.cshtml
@{
    ViewData["Title"] = "All Cars";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using CarDealership.Models
@model IEnumerable<Car>

<h2>Car Inventory</h2>

<table>
    <tr>
        <th>Plate Number</th>
        <th>Lot Number</th>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>Price</th>
        <th>Color</th>
        <th>Condition</th>
        <th>Salesman ID Number</th>
    </tr>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>@car.PlateNumber</td>
                <td>@car.LotID</td>
                <td>@car.Make</td>
                <td>@car.Model</td>
                <td>@car.ModelYear</td>
                <td>@car.Price</td>
                <td>@car.Color</td>
                <td>@car.CarStatus</td>
                <td>@car.SalesmanID</td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Customer" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Customer/Search.cshtml
@{
    ViewData["Title"] = "Car Search";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using CarDealership.Models
@model IEnumerable<Car>

<h2>Search for a car by make and model</h2>

<form action="/Customer/Car" method="get">
    <label for="make">Make:</label>
    <input type="text" name="make"/>
    <br />
    <label for="model">Model:</label>
    <input type="text" name="model" />
    <br />
    <input type="submit" value="Submit">
</form> 

CarDealership/Views/Index/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html>
    <body>
        <div>
            <h1>Car Dealership</h1>

            <a asp-controller="Customer" asp-action="Index">Customer</a>
            <a asp-controller="Staff" asp-action="Index">Staff</a>
    
        </div>
    </body>
</html>

CarDealership/Views/Staff/Add.cshtml
@{
    ViewData["Title"] = "Added";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>The car has been added to inventory</h1>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/AssignSalesman.cshtml
@{
    ViewData["Title"] = "Assigned";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>The selected salesman has been assigned to the car</h1>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/Car.cshtml
@{
    ViewData["Title"] = "View Car Details";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using CarDealership.Models
@model IEnumerable<Car>

<h2>Selected Car</h2>

<table>
    <tr>
        <th>Plate Number</th>
        <th>Lot Number</th>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>Price</th>
        <th>Color</th>
        <th>Condition</th>
        <th>Salesman ID Number</th>
    </tr>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>@car.PlateNumber</td>
                <td>@car.LotID</td>
                <td>@car.Make</td>
                <td>@car.Model</td>
                <td>@car.ModelYear</td>
                <td>@car.Price</td>
                <td>@car.Color</td>
                <td>@car.CarStatus</td>
                <td>@car.SalesmanID</td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/Inventory.cshtml
@{
    ViewData["Title"] = "All Cars";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using CarDealership.Models
@model IEnumerable<Car>

<h2>Car Inventory</h2>

<table>
    <tr>
        <th>Plate Number</th>
        <th>Lot Number</th>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>Price</th>
        <th>Color</th>
        <th>Condition</th>
        <th>Salesman ID Number</th>
    </tr>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>@car.PlateNumber</td>
                <td>@car.LotID</td>
                <td>@car.Make</td>
                <td>@car.Model</td>
                <td>@car.ModelYear</td>
                <td>@car.Price</td>
                <td>@car.Color</td>
                <td>@car.CarStatus</td>
                <th>@car.SalesmanID</th>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/Maintenance.cshtml
@{
    ViewData["Title"] = "Maintenance";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Car has been added to maintenance</h1>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/MoveCar.cshtml
@{
    ViewData["Title"] = "Move";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>The car has been moved</h1>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/Search.cshtml
@{
    ViewData["Title"] = "Car Search";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using CarDealership.Models

@model IEnumerable<Car>

<h2>Search for a car by plate number</h2>

<form action="/Staff/Car" method="get">
    <input type="text" name="plateNum"/>
    <input type="submit" value="Submit">
</form> 

CarDealership/Views/Staff/Sold.cshtml
@{
    ViewData["Title"] = "Sold";
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Congratulations</h1>
<h2>Car has been sold!</h2>

<a asp-controller="Customer" asp-action="Index">Return to Home Page</a>

CarDealership/Views/Staff/Update.cshtml
@{
    Layout = null;
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>The car has been updated</h1>

<a asp-controller="Staff" asp-action="Index">Return to Home Page</a>